# Generated by Django 4.1.1 on 2022-09-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muscle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca de máquina',
                'verbose_name_plural': 'Marcas de máquinas',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre de la máquina')),
                ('type', models.IntegerField(choices=[(0, 'REPS'), (1, 'TIME')], default=0, verbose_name='REPS/TIEMPO')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machinebrand')),
                ('muscle', models.ManyToManyField(blank=True, null=True, to='muscle.muscle')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
    ]
