version: "3.9"

services:
  django_gym_app:
    volumes:
      - ../applications:/app/applications
      - ../assets:/app/assets
      - ../gym_project:/app/gym_project
      - ../static:/app/static
      - ../templates:/app/templates
      - ../.gitingnore:/app/.gitingnore
      - ../manage.py:/app/manage.py
    environment:
      VIRTUAL_HOST: gymapp.cdomingu.cl
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: gymapp.cdomingu.cl
      LETSENCRYPT_EMAIL: cristobaldominguez09@gmail.com
      HTTPS_METHOD: noredirect

    container_name: django_gym_app
    build:
      context: .

    expose:
      - 8000

    env_file:
      - env






networks:
  default:
    name: nginx-proxy


volumes:
  postgres_data:
  static:

