# Generated by Django 4.1.1 on 2022-09-16 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploading_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de carga')),
                ('type', models.IntegerField(choices=[(0, 'REPS'), (1, 'TIME')], default=0, verbose_name='Reps/Time')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
        ),
    ]
