# Generated by Django 4.1.1 on 2022-09-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session.session')),
            ],
            bases=('session.session',),
        ),
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session.session')),
                ('time', models.DurationField(verbose_name='Tiempo')),
            ],
            bases=('session.session',),
        ),
    ]
