# Generated by Django 4.1.1 on 2022-09-18 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_remove_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(verbose_name='Repeticiones')),
                ('intensity', models.PositiveIntegerField(verbose_name='Intesidad/Peso')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
        migrations.AddField(
            model_name='timesession',
            name='gasto',
            field=models.FloatField(default=0, verbose_name='Gasto/Calorías'),
        ),
        migrations.DeleteModel(
            name='RepSession',
        ),
    ]
