# Generated by Django 4.1.1 on 2022-09-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_series_timesession_gasto_delete_repsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesession',
            old_name='gasto',
            new_name='spending',
        ),
    ]
