# Generated by Django 4.1.1 on 2022-09-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_rename_gasto_timesession_spending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AlterModelOptions(
            name='timesession',
            options={'verbose_name': 'Sesión de tiempo', 'verbose_name_plural': 'Sesiones de tiempo'},
        ),
    ]
